# Generated by Django 4.2.6 on 2023-12-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Rechazado'), (2, 'Aceptado')], default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_usuario1', to='usuarios.usuario')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_usuario2', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['usuario1', 'usuario2', 'estado', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistad_usuario1', to='usuarios.usuario')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistad_usuario2', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['usuario1', 'usuario2', 'fecha_inicio'],
            },
        ),
    ]
