# Generated by Django 4.2.6 on 2023-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amistad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudamistad',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Rechazado'), (2, 'Aceptado')], default=0),
        ),
    ]
