# Generated by Django 4.2.6 on 2023-12-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=155)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['nombre', 'fecha_crea', 'creador'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('mod', 'Moderador'), ('miembro', 'Miembro')], default='miembro', max_length=50)),
                ('fecha_entrada', models.DateField(auto_now=True)),
                ('fecha_ult_con', models.DateField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'ordering': ['grupo', 'usuario', 'rol', 'fecha_entrada', 'fecha_ult_con'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Rechazado'), (2, 'Aceptado')], default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'ordering': ['usuario', 'estado', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalaChatGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='MiembrosSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.salachatgrupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='MenChatSalaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('num_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.miembrossala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'ordering': ['num_sala', 'usuario', 'fecha', 'mensaje'],
            },
        ),
    ]
