# Generated by Django 4.2.6 on 2023-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionfile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='apps/publicaciones/filesPublicaciones/'),
        ),
    ]
