# Generated by Django 4.2.6 on 2023-12-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=155)),
                ('nombre', models.CharField(max_length=155)),
                ('apellidos', models.CharField(max_length=155)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('passw', models.CharField(max_length=155)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='apps/usuarios/imagenesPerfil/')),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['email', 'nombre', 'apellidos', 'genero', 'ultima_conexion'],
            },
        ),
    ]
